Repository BF-FrontEnd-class/stop-watch-group-4, pull requests merged in 2023-07, with the labels that each got.

#2 add index.html and style.css
  index.html
  package-lock.json
  styles/style.css
Labels: html, css

#4 add data.js file
  src/data.js
Labels: js

#10 update css
  index.html
  styles/style.css
Labels: css

#9 add components/time.js
  index.html
  src/components/time.js
Labels: js, component-file

#15 separate of concern
  src/events/resetButtonListener.js
  src/events/startButtonListener.js
  src/events/stopButtonListener.js
  src/handlers/resetHandler.js
  src/handlers/startHandler.js
  src/handlers/stopHandler.js
  src/init.js
Labels: js
